name: CI

on:
  push:
    branches: [ add-gh-pages-deploy ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn deploy
