 name: CI

 on:
  push:
    branches:
      - add-gh-pages-deploy

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: add-gh-pages-deploy

      - name: Install
        run: | 
          yarn install
          yarn add gh-pages

      - name: Build
        run: |
          CI=false
          yarn deploy
          
