 name: CI

 on:
  push:
    branches:
      - add-gh-pages-deploy

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: add-gh-pages-deploy

      - name: Install
        run: | 
          yarn install
          yarn add gh-pages
          
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
         credentials: ${{secrets.GIT_CREDENTIAL}}
         
      - name: Build
        env:
          CI: false
        run: |
          export GIT_USER=${{secrets.GIT_USER}}
          git config --global user.name "$GIT_USER"
          git config --global user.email "236687@edu.p.lodz.pl" 
          yarn deploy
