# Created by MichaelCurrin
# https://gist.github.com/MichaelCurrin/a698731096f78240f653faf9a9127cba
 name: Build and deploy 

 on:
  push:
    branches:
      - add-gh-pages-deploy

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@add-gh-pages-deploy
        with:
          persist-credentials: false
          submodules: true

      - name: Install 🔧
        run: yarn install

      - name: Build 🏗️
        run: |
          CI=false
          yarn build
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          
